# Generated by Django 6.1.1 on 2026-09-30 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='commander',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_base', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('balance_date', models.DateField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='assets.base')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipmenttype')),
            ],
            options={
                'unique_together': {('base', 'equipment_type', 'balance_date')},
            },
        ),
    ]
